#!/usr/bin/env bash

set -euo pipefail

export DOCKER_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST \
                           -d "{\"username\": \"${DOCKER_USER}\", \"password\": \"${DOCKER_PASSWORD}\"}" \
                           https://hub.docker.com/v2/users/login/ | jq -r .token)
