#!/usr/bin/env bash

set -euo pipefail

if [ $# -lt 1 ]
then
cat << HELP

docker-tags  --  list all tags with image digests for a Docker image on a remote registry.

EXAMPLE:
    - list all tags for mongooseim:
       docker-tags erlangsolutions/mongooseim

HELP
fi

ORG=${1%%/*}
REPO=${1#*/}

URL="https://hub.docker.com/v2/namespaces/$ORG/repositories/$REPO/tags?page_size=100"
while [ $URL != null ]; do
    RESP=$(curl -s -H "Authorization: JWT ${DOCKER_TOKEN}" "$URL")
    jq -r '.results[] | [.name, ([.images[].digest] | join(";"))] | @tsv' <<< $RESP
    URL=$(jq -r '.next' <<< $RESP)
done
